title: Survivor Team Go!
description: Support. Recover. Thrive.
logo: STG-logo.jpg

theme: jekyll-theme-cayman

links:
- title: home
  url: /
  external: false
- title: episodes
  url: /episodes
- title: about
  url: /about

defaults:
  - scope:
      path: '' # an empty string here means all files in the project
      type: 'posts'
    values:
      layout: 'episode'
      author: 'The Survivor Team'